# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = extractcss
pluginName = ECSStractor
pluginVersion = 1.1.262

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild = 262

platformType = WS
platformVersion = 2026.2
platformDownloadSources = true

platformBundledPlugins = com.intellij.css, JavaScript, com.intellij.modules.json

# Gradle Wrapper
gradleVersion = 9.4.0

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
