# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = extractcss
pluginName = ECSStractor
pluginVersion = 1.1.254
pluginSinceBuild = 261
pluginUntilBuild = 261.*
pluginVerifierIdeVersions = 2026.1
platformVersion = 2026.1
platformDownloadSources = true

platformBundledPlugins = com.intellij.css, JavaScript

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
