# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = extractcss
pluginName = ECSStractor
pluginVersion = 1.1.261

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild = 261
pluginUntilBuild = 261.*

# Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
# See https://jb.gg/intellij-platform-builds-list for available build versions.
pluginVerifierIdeVersions = 261.22158.121

platformType = IU
platformVersion = 261.22158.121
platformDownloadSources = true

platformBundledPlugins = com.intellij.css, JavaScript, com.intellij.modules.json

# Gradle Wrapper
gradleVersion = 9.4.0

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
